---
name: harper-ls
description: |
  Harper is an English grammar checker designed to be just right. I created it after years of dealing with the shortcomings of the competition.
homepage: https://github.com/elijah-potter/harper
licenses:
  - Apache-2.0
languages:
  - Text
  - Markdown
categories:
  - Linter

source:
  id: pkg:cargo/harper-ls@0.11.0

bin:
  harper-ls: cargo:harper-ls
